# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-28 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='GameDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=128, null=True, unique=True, verbose_name='游戏名称')),
                ('name_alias', models.CharField(max_length=256, null=True, verbose_name='游戏下载别名')),
                ('poster', models.CharField(max_length=256, null=True, verbose_name='海报')),
                ('grade', models.FloatField(max_length=10, null=True, verbose_name='游戏评分')),
                ('introduce', models.TextField(max_length=256, null=True, verbose_name='游戏介绍')),
                ('down_url', models.CharField(max_length=256, null=True, verbose_name='详情页链接链接')),
                ('BT_link', models.CharField(max_length=256, null=True, verbose_name='BT链接')),
                ('game_link', models.CharField(max_length=256, null=True, verbose_name='游戏下载地址')),
                ('baiduyun', models.CharField(max_length=256, null=True, verbose_name='百度云下载地址')),
                ('tag', models.CharField(max_length=256, null=True, verbose_name='游戏标签')),
                ('sell', models.CharField(max_length=256, null=True, verbose_name='发售时间')),
                ('size', models.CharField(max_length=256, null=True, verbose_name='游戏大小')),
                ('picture_min', models.TextField(max_length=256, null=True, verbose_name='游戏截图缩略图')),
                ('picture_max', models.TextField(max_length=256, null=True, verbose_name='游戏截图大图')),
                ('gameclass', models.ForeignKey(max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='download.GameClass', verbose_name='游戏类型')),
            ],
            options={
                'verbose_name': '游戏信息',
                'verbose_name_plural': '游戏信息',
            },
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publistshers_name', models.CharField(max_length=128, null=True, unique=True, verbose_name='游戏厂商')),
            ],
            options={
                'verbose_name': '游戏厂商',
                'verbose_name_plural': '游戏厂商',
            },
        ),
        migrations.AddField(
            model_name='gamedetails',
            name='publishers',
            field=models.ForeignKey(max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='download.Publishers', verbose_name='游戏厂商'),
        ),
    ]
