# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-28 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameclass',
            name='picture',
            field=models.CharField(max_length=128, null=True, verbose_name='游戏分类图片'),
        ),
        migrations.AddField(
            model_name='gameclass',
            name='type_name',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='游戏分类'),
        ),
    ]
